# ui
ui <- fluidPage(
  theme = shinytheme("flatly"),
  navbarPage("Rhode Island COVID-19",
             navbarMenu("Town/City Information",
                        tabPanel("Animated Rhode Island Map",
                                 fluidPage(
                                   titlePanel("Animated Rhode Island Map:"),
                                   fluidRow(
                                     column(4,
                                            sliderInput("rhody_animate_date", "Date:", 
                                                        min(town_data$Date),
                                                        max(town_data$Date),
                                                        value = max(town_data$Date),
                                                        step = 1,
                                                        animate= TRUE)),
                                     column(4, 
                                            selectInput("rhody_animated_map_town",
                                                        "Specific City/Town Information:",
                                                        unique(as.character(town_data$Town))))),
                                   h4(textOutput("rhody_animate_date")),
                                   leafletOutput("rhody_map_animate"),
                                   h4("State Statistics:"),
                                   fluidRow(
                                     column(2, 
                                            h5(textOutput("rhody_animate_cases"))),
                                     column(2,
                                            h5(textOutput("rhody_animate_state_new_cases"))),
                                     column(4,
                                            h5(textOutput("rhody_animate_state_hospitalization"))),
                                     column(4, 
                                            h5(textOutput("rhody_animate_state_mortality")))),
                                   h4(textOutput("rhody_animate_town_name")),
                                   fluidRow(
                                     column(2,
                                            h5(textOutput("rhody_animate_town_cases"))),
                                     column(2,
                                            h5(textOutput("rhody_animate_town_new_cases"))),
                                     column(4, 
                                            h5(textOutput("rhody_animate_town_cases_per_resident"))),
                                     column(4,
                                            h5(textOutput("rhody_animate_town_cases_state")))))),
                        
                        tabPanel("Detailed Rhode Island Map:",
                                 titlePanel("Detailed Rhode Island Map:"),
                                 h4("(click on city/town for more information)"),
                                 fluidRow(
                                   column(3,
                                          selectInput("rhody_map_date",
                                                      "Date:",
                                                      unique(as.character(town_data$Date)),
                                                      selected = max(town_data$Date)))),
                                 leafletOutput("rhody_map"),
                                 
                                 hr(),
                                 sidebarLayout(
                                   sidebarPanel(
                                     selectInput("rhody_detailed_graph_city_town",
                                                 "City/Town:",
                                                 unique(as.character(town_data$Town))),
                                     selectInput("rhody_detailed_graph_start_date",
                                                 "Start Date:",
                                                 unique(as.character(town_data$Date))),
                                     selectInput("rhody_detailed_graph_end_date",
                                                 "End Date:",
                                                 c("All",
                                                   unique(as.character(town_data$Date))))),
                                   mainPanel(                                 
                                     titlePanel("City/Town Graphs:"),
                                     h4('(City/Towns that have ">5" cases are given a value of 2)'),
                                     plotlyOutput("rhody_map_town_detailed")))),
                        tabPanel("City/Town Data:",
                                 titlePanel("Town Data Table:"),
                                 fluidRow(
                                   column(3,
                                          selectInput("town_start_date",
                                                      "Start Date:",
                                                      c("All",
                                                        unique(as.character(town_data$Date))))
                                   ),
                                   column(3,
                                          selectInput("town_end_date",
                                                      "End Date:",
                                                      c("All",
                                                        unique(as.character(town_data$Date))))
                                   ),
                                   column(3,
                                          selectInput("Town_Selected",
                                                      "City/Town:",
                                                      c("All",
                                                        unique(as.character(town_data$Town))))
                                   ),
                                   column(3,
                                          selectInput("County_Selected",
                                                      "County:",
                                                      c("All",
                                                        unique(as.character(town_data$County))))
                                   )),
                                 DT::dataTableOutput("rhody_map_table"))),
             navbarMenu("State Data",
                        tabPanel("Cases",
                                 fluidPage(
                                   sidebarLayout(
                                     sidebarPanel(
                                       radioButtons("cases_plot_type",
                                                    "Plot Type:",
                                                    c("Line", "Bar")),
                                       selectInput("cases_start_date",
                                                   "Start Date:",
                                                   c(unique(as.character(new_cases_long$Date)))),
                                       selectInput("cases_end_date",
                                                   "End Date",
                                                   c("All",
                                                     unique(as.character(new_cases_long$Date))))),
                                     mainPanel(
                                       plotlyOutput("rhody_confirmed_cases"),
                                       fluidRow(
                                         column(4,
                                                selectInput("cases_table_start_date",
                                                            "Start Date:",
                                                            c(unique(as.character(new_cases_long$Date))))),
                                         column(4,
                                                selectInput("cases_table_end_date",
                                                            "End Date:",
                                                            c("All",
                                                              unique(as.character(new_cases_long$Date)))))),
                                       DT::dataTableOutput("rhody_confirmed_cases_table"))))),
                        tabPanel("Age",
                                 fluidPage(
                                   sidebarLayout(
                                     sidebarPanel(
                                       radioButtons("age_plot_type", "Data Type:",
                                                    c("Aggregate", "Percentage")),
                                       selectInput("age_start_date",
                                                   "Start Date:",
                                                   unique(as.character(age_data$Date)),
                                                   selected = as.character(max(age_data$Date))),
                                       selectInput("age_end_date",
                                                   "End Date:",
                                                   c("All", unique(as.character(age_data$Date))))),
                                     mainPanel(
                                       plotlyOutput("Age_Plot"),
                                       fluidRow(
                                         column(4, 
                                                selectInput("age_table_start_date",
                                                            "Start Date:",
                                                            c(unique(as.character(age_data$Date))))),
                                         column(4, 
                                                selectInput("age_table_end_date",
                                                            "Date:",
                                                            c("All",
                                                              unique(as.character(age_data$Date))))),
                                         column(4,
                                                selectInput("age_age_category",
                                                            "Age Category:",
                                                            c("All", unique(age_data$Age_Category))))),
                                       DT::dataTableOutput("age_table"))))),
                        tabPanel("Gender",
                                 fluidPage(
                                   sidebarLayout(
                                     sidebarPanel(
                                       radioButtons("gender_plot_type", "Data Type:",
                                                    c("Aggregate", "Percentage")),
                                       selectInput("gender_plot_start_date",
                                                   "Start Date:",
                                                   unique(as.character(gender_data$Date)),
                                                   selected = as.character(max(gender_data$Date))),
                                       selectInput("gender_plot_end_date",
                                                   "End Date:",
                                                   c("All", unique(as.character(gender_data$Date)))),
                                       selectInput("gender_plot_gender",
                                                   "Gender:",
                                                   c("All", unique(gender_data$Gender)))),
                                     mainPanel(
                                       # Plot
                                       plotlyOutput("gender_plot"),
                                       fluidRow(
                                         column(4, 
                                                selectInput("gender_table_start_date",
                                                            "Date:",
                                                            unique(as.character(gender_data$Date)))),
                                         column(4, 
                                                selectInput("gender_table_end_date",
                                                            "End Date:",
                                                            c("All", unique(as.character(gender_data$Date))))),
                                         column(4, 
                                                selectInput("gender_table_gender",
                                                            "Gender:",
                                                            c("All",
                                                              unique(as.character(gender_data$Gender)))))),
                                       DT::dataTableOutput("gender_table"))))),
                        tabPanel("Hospitalization",
                                 fluidPage(
                                   sidebarLayout(
                                     sidebarPanel(
                                       radioButtons("hospital_plot_type", "Plot Type:",
                                                    c("Line Graph", "Bar Graph")),
                                       radioButtons("hospital_data_type", "Data Type:",
                                                    c("Aggregate", "Percentage")),
                                       selectInput("hospital_plot_start_date",
                                                   "Start Date:",
                                                   unique(as.character(hospital_data$Date))),
                                       selectInput("hospital_plot_end_date",
                                                   "End Date:",
                                                   c("All", 
                                                     unique(as.character(hospital_data$Date)))),
                                       selectInput("hospital_plot_category",
                                                   "Category:",
                                                   c("All",
                                                     unique(hospital_data$Category)))),
                                     mainPanel(
                                       # Plot
                                       plotlyOutput("hospital_plot"),
                                       # Table
                                       fluidRow(
                                         column(4, 
                                                selectInput("hospital_table_start_date",
                                                            "Start Date:",
                                                            unique(as.character(hospital_data$Date)))),
                                         column(4, 
                                                selectInput("hospital_table_end_date",
                                                            "End Date:",
                                                            c("All",
                                                              unique(as.character(hospital_data$Date))))),
                                         column(4,
                                                selectInput("hospital_table_category",
                                                            "Category:",
                                                            c("All", 
                                                              unique(as.character(hospital_data$Category)))))),
                                       DT::dataTableOutput("rhody_hospital_table")))))),
             navbarMenu("Information",
                        tabPanel("Information",
                                 fluidPage(
                                   includeMarkdown("https://raw.githubusercontent.com/jjenki22/Rhode-Island-COVID-19/master/Markdowns/Information.md"))),
                        tabPanel("Town/City Information",
                                 fluidPage(
                                   includeMarkdown("https://raw.githubusercontent.com/jjenki22/Rhode-Island-COVID-19/master/Markdowns/Town%20Information.md"))),
                        tabPanel("About",
                                 fluidPage(
                                   includeMarkdown("https://raw.githubusercontent.com/jjenki22/Rhode-Island-COVID-19/master/Markdowns/About.md"))))))
